### ISSUE TITLE
How to downgrade remaster to 1.16.1?

### ISSUE THREAD

**Issue by luohc2004** [suegy/bwapi-mono-bridge2#1]
the way introduced in wiki [StarCraft Remastered Setup BWAPI
](https://github.com/suegy/bwapi-mono-bridge2/wiki/StarCraft-Remastered-Setup-BWAPI) is actually using the files laid in remaster but install a fully new standard version of starcraft orginal.

**Comment by suegy** [comment]
You are using Remastered as a base to get SC-BW because when I wrote this guide Remaster did not support BWAPI. 
The main difference is that Remastered has nicer graphics which you normally don't need when running the AI.

**Comment by luohc2004** [comment]
I got it! Thanks a lot!
